### ISSUE TITLE
Mentioning roles and members.

### ISSUE THREAD

**Issue by DankMemz69** [oskarscot/DiscordIntegration#2]
You can still mentions roles and members.
By typing `<@` or `<@!` then the user ID you can mention members.
By typing `<@&` then the role ID you can mention entire roles.

**Comment by oskarscot** [comment]
> You can still mentions roles and members. By typing `<@` or `<@!` then the user ID you can mention members. By typing `<@&` then the role ID you can mention entire roles.

I'll fix it soon, thx

**Comment by oskarscot** [comment]
Fixed, thanks for reporting
